// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Node interface {
	IsNode()
}

type Comment struct {
	// ID
	ID string `json:"id"`
	// コメント内容
	Content string `json:"content"`
	// コメント投稿者
	Commenter *User `json:"commenter"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type Post struct {
	// ID
	ID string `json:"id"`
	// タイトル
	Title string `json:"title"`
	// 本文
	Body string `json:"body"`
	// 投稿日時
	PostedAt time.Time `json:"postedAt"`
	// 記事コメント
	Comments []*Comment `json:"comments"`
	// 記事投稿者
	Poster *User `json:"poster"`
}

type User struct {
	// ID
	ID string `json:"id"`
	// ユーザー名
	Name string `json:"name"`
}
