version: '3'

services:

  mysql:
    build: .docker/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    expose:
      - "13306"
    ports:
      - "13306:3306"